name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *" # every midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: tju-yxq
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg

      - name: Push to output branch
        run: |
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update contribution snake"
          git branch -M output
          git remote add origin "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push --force origin output
